export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const SET_NULL_REGISTER_ERROR = "SET_NULL_REGISTER_ERROR";
export const SET_NULL_LOGIN_ERROR = "SET_NULL_LOGIN_ERROR";

export const SEND_LISTENED_TRACK_SUCCESS = "SEND_LISTENED_TRACK_SUCCESS";
export const SEND_LISTENED_TRACK_ERROR = "SEND_LISTENED_TRACK_ERROR";

export const FETCH_TRACK_HISTORY_REQUEST = "FETCH_TRACK_HISTORY_REQUEST";
export const FETCH_TRACK_HISTORY_SUCCESS = "FETCH_TRACK_HISTORY_SUCCESS";
export const FETCH_TRACK_HISTORY_ERROR = "FETCH_TRACK_HISTORY_ERROR";

export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";
